name: meals_and_drinks_api_client
description: A client to perform meals and drinks API calls
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.0.0 
  flutter_test:
    sdk: flutter 
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  